### ISSUE TITLE
Update text showing number of features in tables

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/wetlandPlants#10]
@jjhi11 

Each table shows the number of features with a sentence like: "Showing attributes for 3 species." I'd like to make sure this text is correct for all of the tables so that tables that list species refer to species and tables that list sites refer to sites.

1. Click on site, then project, text should be "Showing attributes for 1 project"
2. Click on site, then species, text should be "Showing attributes for # species" (currently correct)
3. Select sites by Attributes, Open table, text should be "Showing attributes for # sites"
4. Select sites by Attributes, summary of species, text should be "Showing attributes for # species at # sites"
5. Search sites by Species, text should be "Showing attributes for 445 species"
6. When using the search by polygon function, the resulting table should say "Showing attributes for # sites"

**Comment by jjhi11** [comment]
@marshallrobinson please check functionality

**Comment by marshallrobinson** [comment]
> 5\. Search sites by Species, text should be "Showing attributes for 445 species"

I can't figure out how to get the Search Sites by Species to say this. For me, it says "Showing attributes for # species at # sites." Is this correct? @wetlandsDiane

**Comment by dmenuz** [comment]
> > 5. Search sites by Species, text should be "Showing attributes for 445 species"
> 
> I can't figure out how to get the Search Sites by Species to say this. For me, it says "Showing attributes for # species at # sites." Is this correct? @wetlandsDiane

@marshallrobinson 

That is what I see, too. that is incorrect, but what I wrote is incorrect as well. What is should say is "Showing attributes for # sites"

**Comment by jjhi11** [comment]
@marshallrobinson @dmenuz check now

**Comment by marshallrobinson** [comment]
All looks good to me now.
