### ISSUE TITLE
Improving the table that results from the Search Site by Species query 

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/wetlandPlants#12]
@jjhi11 

Right now when you run the Search Site by Species query, you get a list of all sites with a particular species. Can you make it so when you click on a site in the table, you can then zoom to the site on the map and click on the projects or species tables in the associated pop-up? I think sometimes a person will run that query and then want more information about a particular site that comes up on the list, but right now there is no easy way to get to that site. 

The fix should be the same as how the Search Site by Attributes Open Table query works, where you can get to any site in the resulting table by clicking on it.

This was one of the requests from the external reviewers.

Also, can you allow users to sort the fields in the table? Other tables allow that to happen, but not this one.

**Comment by jjhi11** [comment]
@marshallrobinson please check functionality

**Comment by marshallrobinson** [comment]
Looks good to me.

@wetlandsDiane, what do you think?

**Comment by dmenuz** [comment]
Looks good to me, too! Thanks!
