### ISSUE TITLE
Update field name in application

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/wetlandPlants#30]
Hello,

Currently one of the field shows up as Project Wetland Class in the data tables. Can we update this to say "HGM Class" instead? This change would need to occur in both the sites table and the join table.

Thanks
Diane

**Comment by marthajensen** [comment]
@wetlandsDiane I am going to change the field to hgm_class in the database in both the sites and the outjoin. The plan is for the field to appear as "HGM Class" in the application but I wanted to let you know the underlying data will be changing as well

**Comment by marthajensen** [comment]
done
