### ISSUE TITLE
Update the Database Contents text

### ISSUE THREAD

**Issue by wetlandsDiane** [UGS-GIO/wetlandPlants#7]
There are some minor changes I'd like to make to the Database Contents text, mostly to align the description with the updated data format in the mapper. The requested changes are in bold below.

***NOTE! You cannot just copy and paste the text below into the Database Contents panel. I am only including the blocks of text where there are changes and I didn't include links or other formatting elements.***

# WETLAND CLASSIFICATION

Wetland **types** are presented by ecoregion, areas where ecosystems are generally similar based on patterns in geology, landforms, soils, vegetation, climate, land use, wildlife, and hydrology. Ecoregions are hierarchically arranged at four levels with 2 level I ecoregions, 3 level II ecoregions, 7 level III ecoregions, and 36 level IV ecoregions in Utah. Three level III ecoregions make up more than 95% of Utah, including the Central Basin and Range, the Wasatch and Uinta Mountains, and the Colorado Plateau. The majority of wetland survey data contributed to this application to date have been from the first two level III ecoregions, so wetland classes for now focus on those two ecoregions only. Within each ecoregion, wetland sites were further classified based on factors such as dominant overstory life form (herbaceous, shrub, tree), water regime, and landscape position. For the Wasatch and Uinta Mountains, we also use level IV ecoregions as a factor in the classification. **Sites with substantial mixing of two wetland types are assigned both a primary and secondary wetland type.**

## Basin and Range
Data **were** used from 204 sites surveyed in the Central Basin and Range by the UGS between 2013 and 2018 to develop seven initial wetland classes that take into account dominant overstory life form, water regime, salinity tolerance, and landscape position. More information about the development of the Central Basin and Range classes can be found here. It is anticipated that these wetland classes will be modified in 2020 at the conclusion of a two-year study of wetlands in the Central Basin and Range of Utah.

### Table elements under Basin and Range
For emergent marsh, update to say: Wetland dominated by emergent forbs and graminoids and frequently inundated with water ≥15 cm in depth **and typically saturated when not inundated**, though water depths may vary throughout the year **depending on climate conditions and management.**

For woody wetland, update to say: Wetland dominated by woody species, typically with ≥20% woody species cover, **and frequently found along streams and river.**

# VEGETATION CONDITION
Sites were assigned vegetation condition classes based solely on plant community composition data. “Reference” sites are sites with the most intact plant communities for a particular wetland class, regardless of the degree of landscape disturbance adjacent to these sites or whether other stressors are present. **Cover-weighted mean C was used to assign sites to classify sites. Cover-weighted mean C is a metric** that relies on coefficient of conservatism values (C-values). C-values between 1 and 10 are assigned to species based on their association with disturbance through a combination of best professional judgment, literature review, and/or field observations. Low values indicate that species are usually found at disturbed sites, high values indicate that species are associated with pristine sites, and values in the middle indicate that species may be found equally at either type of site. All non-native species are assigned a C-value of 0. **Cover-weighted mean C is calculated by taking an average C-value for all species at a site, weighted by the cover of each species.**
**“Reference” sites are those sites with a cover-weighted mean C value within the top 25% of sites for the wetland class, using all data available in May 2020. Sites where <75% of the species cover were assigned C-values were classified as “not enough data.” We did not classify any sites as reference for aquatic bed wetlands, sites with no vegetation, or wetland classes having <10 sites; these sites were all classified as “not enough data.” Sites with two wetland types were considered reference if they met or exceeded the cover-weighted mean C thresholds for both types.**

**Comment by marshallrobinson** [comment]
> Cover-weighted mean C was used to assign sites to classify sites.

Is this what the sentence in the "Vegetation Condition" paragraph is supposed to say? It doesn't sound right to me.

**Comment by wetlandsDiane** [comment]
You are correct, Marshall, that sentence is not correct.

See the sentence below:

Cover-weighted mean C was used to assign sites to **vegetation condition classes.**
